### ISSUE TITLE
Intrinsics code not linked out in Blazor sample

### ISSUE THREAD

**Issue by CoffeeFlux** [mono/linker#1615]
When creating a new Blazor sample (`dotnet new blazorwasm`) and publishing in release, the linked corelib appears to still have lots of entries in `System.Runtime.Intrinsics.*`, which are kept around because of a call to `System.Runtime.Intrinsics.Vector128`. This appears to be used in `Utf8Utility.GetPointerToFirstInvalidByte`, but is guarded behind a call to `AdvSimd.Arm64.IsSupported` and ought to be linked out.

**Comment by vitek-karas** [comment]
This has been fixed in https://github.com/dotnet/runtime/pull/43537. The fix didn't make 5.0 RTM. But in 6.0 it's there - I haven't validated by building against latest 6.0, but the code is missing from corelib in local build (so it won't be there when trimmed in an app).

**Comment by akoeplinger** [comment]
@vitek-karas I still see the intrinsics code in System.Private.CoreLib.dll in dotnet/runtime using the wasm sample we have. Maybe it's being kept due to some other code path. It shouldn't need the 6.0 SDK right?

**Comment by akoeplinger** [comment]
the types only have the `IsSupported` property in them though. not sure if the linker should strip out those too?

**Comment by akoeplinger** [comment]
Hm looks like this is intentional: https://github.com/mono/linker/issues/1106
